# Generated by Django 4.2.6 on 2023-10-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_datas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datas',
        ),
        migrations.AddField(
            model_name='sathick',
            name='degree',
            field=models.CharField(default='', max_length=20),
        ),
    ]
