# Generated by Django 4.2.6 on 2023-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_datas_sathick_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Mail', models.CharField(max_length=50)),
            ],
        ),
    ]
